version: 1
disable_existing_loggers: false

formatters:
  json:
    format: '{"t":"%(asctime)s","l":"%(levelname)s","m":"%(message)s","n":"%(name)s"}'
    datefmt: "%Y-%m-%dT%H:%M:%SZ"
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: DEBUG
    stream: ext://sys.stdout
    
root:
  handlers: [console]
  level: INFO